### ISSUE TITLE
Install Instructions?

### ISSUE THREAD

**Issue by j450h1** [barnybug/tesla-cli#1]
How do you install this?

**Comment by franky436** [comment]
go install github.com/barnybug/tesla-cli/cmd/tesla@latest
go run github.com/barnybug/tesla-cli/cmd/tesla@latest login
...

**Comment by j450h1** [comment]
It worked! One thing to add - make sure you are using the latest version of go (otherwise you might get an error): https://go.dev/doc/install

You can check the version of go as such: `go version`

Confirmed working with: **go version go1.19.4 darwin/amd64**
